[simulate]
chrom-sizes="changeme"
output-prefix="changeme"
bin-size=5000
target-contact-density=1.0
lefs-per-mbp=20
ncells=104
extrusion-barrier-file="changeme"
quiet=true
threads="changeme"
seed=5387900181139535693
