[simulate]
chrom-sizes="changeme"
output-prefix="changeme"
bin-size=5000
target-contact-density=1
lefs-per-mbp=20
ncells=256
extrusion-barrier-file="changeme"
randomize-contacts=true
quiet=true
threads="changeme"
seed=5387900181139535693
