[simulate]
chrom-sizes="GRCh38.chrom.sizes"
output-prefix="GRCh38_HeLa_all_CTCF_sites"
bin-size=5000
target-contact-density=1.0
lefs-per-mbp=20
ncells=256
extrusion-barrier-file="GRCh38_HeLa_CTCF_sites_filtered.bed.gz"
extrusion-barrier-occupancy=0.82
ctcf-not-occupied-probability-of-transition-to-self=0.6
randomize-contacts=true
