[simulate]
chrom-sizes="changeme"
extrusion-barrier-file="changeme"
output-prefix="GRCh38_H1_modle_heatmaps_comparison_tad_only"
bin-size=5000
target-contact-density=20.0
lefs-per-mbp=20
keep-chrom-without-barriers=true
contact-sampling-strategy="tad-only-with-noise"
