# Copyright (C) 2022 Roberto Rossini <roberros@uio.no>
#
# SPDX-License-Identifier: MIT

[simulate]
bin-size=5000
target-contact-density=20.0
keep-chrom-without-barriers=true
contact-sampling-strategy="tad-plus-loop-with-noise"
