# Copyright (C) 2022 Roberto Rossini <roberros@uio.no>
#
# SPDX-License-Identifier: MIT

[simulate]
bin-size=5000
target-contact-density=6.0
keep-chrom-without-barriers=true
contact-sampling-strategy="tad-plus-loop-with-noise"
avg-lef-processivity=300000
output-prefix="GRCh38_prob_decay_normal_proc_tad_plus_loop"
diagonal-width=10000000
