# Copyright (C) 2022 Roberto Rossini <roberros@uio.no>
#
# SPDX-License-Identifier: MIT

[simulate]
bin-size=5000
target-contact-density=6.0
keep-chrom-without-barriers=true
contact-sampling-strategy="tad-only-with-noise"
avg-lef-processivity=600000
output-prefix="GRCh38_prob_decay_high_proc_tad_only"
diagonal-width=10000000
