# Copyright (C) 2022 Roberto Rossini <roberros@uio.no>
#
# SPDX-License-Identifier: MIT

[simulate]
chrom-sizes="changeme"
extrusion-barrier-file="changeme"
output-prefix="GRCh38_H1_modle_heatmap_comparison_loop_only"
bin-size=5000
target-contact-density=20.0
lefs-per-mbp=20
keep-chrom-without-barriers=true
contact-sampling-strategy="loop-only-with-noise"
