# Copyright (C) 2022 Roberto Rossini <roberros@uio.no>
#
# SPDX-License-Identifier: MIT

[simulate]
chrom-sizes="changeme"
extrusion-barrier-file="changeme"
output-prefix="GRCh38_H1_modle_heatmap_comparison_wapl_kd"
bin-size=5000
target-contact-density=10.0
lefs-per-mbp=20
keep-chrom-without-barriers=true
avg-lef-processivity=3000000
diagonal-width=6000000
contact-sampling-strategy="tad-plus-loop-with-noise"
