[simulate]
chrom-sizes="changeme"
extrusion-barrier-file="changeme"
output-prefix="GRCh38_H1_modle_heatmaps_comparison_wapl_kd"
bin-size=5000
target-contact-density=20.0
lefs-per-mbp=20
keep-chrom-without-barriers=true
prob-of-lef-release=0.0015
diagonal-width=6000000
contact-sampling-strategy="tad-plus-loop-with-noise"
